//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaDashboard.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialMediaDashboard.Domain.Resources.ValidatorResource", typeof(ValidatorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MS SQL Server connection string format..
        /// </summary>
        public static string ConnectionMsSqlServerInvalid {
            get {
                return ResourceManager.GetString("ConnectionMsSqlServerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PostgreSQL connection string format, .
        /// </summary>
        public static string ConnectionPostgreSqlInvalid {
            get {
                return ResourceManager.GetString("ConnectionPostgreSqlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size is larger than the allowed one (size should not exceed 20 Kb)..
        /// </summary>
        public static string FileMaximumLength {
            get {
                return ResourceManager.GetString("FileMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type is not allowed..
        /// </summary>
        public static string FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("FileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid secret format, use: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..
        /// </summary>
        public static string JwtSecretInvalid {
            get {
                return ResourceManager.GetString("JwtSecretInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token lifetime format, use: hh:mm:ss..
        /// </summary>
        public static string JwtTokenLifetimeInvalid {
            get {
                return ResourceManager.GetString("JwtTokenLifetimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address value..
        /// </summary>
        public static string MailAddressInvalid {
            get {
                return ResourceManager.GetString("MailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password value..
        /// </summary>
        public static string MailPasswordInvalid {
            get {
                return ResourceManager.GetString("MailPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port value, must be: 25, 465 or 587..
        /// </summary>
        public static string MailPortInvalid {
            get {
                return ResourceManager.GetString("MailPortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mail server value..
        /// </summary>
        public static string MailServerInvalid {
            get {
                return ResourceManager.GetString("MailServerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid use SSL value, must be: true or false..
        /// </summary>
        public static string MailUseSslInvalid {
            get {
                return ResourceManager.GetString("MailUseSslInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date birth value, there should be more or equal 1970-01-01..
        /// </summary>
        public static string ProfileBirthDateInvalid {
            get {
                return ResourceManager.GetString("ProfileBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gender format..
        /// </summary>
        public static string ProfileGenderInvalid {
            get {
                return ResourceManager.GetString("ProfileGenderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Dsn value..
        /// </summary>
        public static string SentryDsnInvalid {
            get {
                return ResourceManager.GetString("SentryDsnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum breadcrumb level..
        /// </summary>
        public static string SentryMinimumBreadcrumbLevelInvalid {
            get {
                return ResourceManager.GetString("SentryMinimumBreadcrumbLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum event level..
        /// </summary>
        public static string SentryMinimumEventLevelInvalid {
            get {
                return ResourceManager.GetString("SentryMinimumEventLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password of Instagram account..
        /// </summary>
        public static string SocialNetworkInstagramAccountPasswordInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkInstagramAccountPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username of Instagram account..
        /// </summary>
        public static string SocialNetworkInstagramAccountUsernameInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkInstagramAccountUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Vk access token..
        /// </summary>
        public static string SocialNetworkVkAccessTokenInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkVkAccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid YouTube access token..
        /// </summary>
        public static string SocialNetworkYouTubeAccessTokenInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkYouTubeAccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account name..
        /// </summary>
        public static string SubscriptionAccountNameInvalid {
            get {
                return ResourceManager.GetString("SubscriptionAccountNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name is required..
        /// </summary>
        public static string SubscriptionAccountNameRequired {
            get {
                return ResourceManager.GetString("SubscriptionAccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription type identifier..
        /// </summary>
        public static string SubscriptionTypeIdInvalid {
            get {
                return ResourceManager.GetString("SubscriptionTypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string UserConfirmPasswordNotMatch {
            get {
                return ResourceManager.GetString("UserConfirmPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        public static string UserConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("UserConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string UserEmailInvalid {
            get {
                return ResourceManager.GetString("UserEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should be from {0} to {1}..
        /// </summary>
        public static string UserNameShort {
            get {
                return ResourceManager.GetString("UserNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required..
        /// </summary>
        public static string UserRefreshTokenRequired {
            get {
                return ResourceManager.GetString("UserRefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required..
        /// </summary>
        public static string UserTokenRequired {
            get {
                return ResourceManager.GetString("UserTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code is required..
        /// </summary>
        public static string UserVerifyCodeRequired {
            get {
                return ResourceManager.GetString("UserVerifyCodeRequired", resourceCulture);
            }
        }
    }
}
