//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaDashboard.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialMediaDashboard.Domain.Resources.ValidatorResource", typeof(ValidatorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MS SQL Server connection string format..
        /// </summary>
        public static string ConnectionMsSqlServerInvalid {
            get {
                return ResourceManager.GetString("ConnectionMsSqlServerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PostgreSQL connection string format, .
        /// </summary>
        public static string ConnectionPostgreSqlInvalid {
            get {
                return ResourceManager.GetString("ConnectionPostgreSqlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid secret format, use: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..
        /// </summary>
        public static string JwtSecretInvalid {
            get {
                return ResourceManager.GetString("JwtSecretInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token lifetime format, use: hh:mm:ss..
        /// </summary>
        public static string JwtTokenLifetimeInvalid {
            get {
                return ResourceManager.GetString("JwtTokenLifetimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required..
        /// </summary>
        public static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Dsn value..
        /// </summary>
        public static string SentryDsnInvalid {
            get {
                return ResourceManager.GetString("SentryDsnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum breadcrumb level..
        /// </summary>
        public static string SentryMinimumBreadcrumbLevelInvalid {
            get {
                return ResourceManager.GetString("SentryMinimumBreadcrumbLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid minimum event level..
        /// </summary>
        public static string SentryMinimumEventLevelInvalid {
            get {
                return ResourceManager.GetString("SentryMinimumEventLevelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password of Instagram account..
        /// </summary>
        public static string SocialNetworkInstagramAccountPasswordInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkInstagramAccountPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username of Instagram account..
        /// </summary>
        public static string SocialNetworkInstagramAccountUsernameInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkInstagramAccountUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Vk access token..
        /// </summary>
        public static string SocialNetworkVkAccessTokenInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkVkAccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid YouTube access token..
        /// </summary>
        public static string SocialNetworkYouTubeAccessTokenInvalid {
            get {
                return ResourceManager.GetString("SocialNetworkYouTubeAccessTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account name..
        /// </summary>
        public static string SubscriptionAccountNameInvalid {
            get {
                return ResourceManager.GetString("SubscriptionAccountNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subscription type identifier..
        /// </summary>
        public static string SubscriptionTypeIdInvalid {
            get {
                return ResourceManager.GetString("SubscriptionTypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required..
        /// </summary>
        public static string TokenRequired {
            get {
                return ResourceManager.GetString("TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be from {0} to {1}..
        /// </summary>
        public static string UsernameShort {
            get {
                return ResourceManager.GetString("UsernameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code is required..
        /// </summary>
        public static string VerifyCodeRequired {
            get {
                return ResourceManager.GetString("VerifyCodeRequired", resourceCulture);
            }
        }
    }
}
