enum ActionTypes {
    ON_LOGIN = 'ON_LOGIN',
    ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS',
    ON_LOGIN_ERROR = 'ON_LOGIN_ERROR',

    ON_LOGOUT = 'ON_LOGOUT',
    ON_LOGOUT_SUCCESS = 'ON_LOGOUT_SUCCESS',
    ON_LOGOUT_ERROR = 'ON_LOGOUT_ERROR',
}

export default ActionTypes;